Repository lzaycoe/brainbox-backend, pull requests merged in 2025-02, with the labels that each got.

#11 release: release v1.0.1
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorators/roles.decorator.ts
  src/auth/dto/auth.admin.dto.ts
  src/auth/enums/role.enum.ts
  src/auth/guards/admin.guard.ts
  src/auth/guards/jwt-access.guard.ts
  src/auth/guards/jwt-refresh.guard.ts
  src/auth/guards/role.guard.ts
  src/auth/interfaces/jwt-refresh-payload.interface.ts
  src/auth/interfaces/user.interface.ts
  src/auth/strategies/admin.strategy.ts
  src/auth/strategies/jwt-access.strategy.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/configs/jwt-access.config.ts
  src/configs/jwt-refresh.config.ts
  src/domains/admins/admins.controller.ts
  src/domains/admins/admins.module.ts
  src/domains/admins/admins.service.ts
  src/domains/admins/dto/create-admin.dto.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/domains.module.ts
  src/main.ts
  src/middlewares/morgan.middleware.ts
  src/providers/clerk.service.ts
  src/providers/prisma.service.ts
  src/swagger/setup.ts
  src/utils/hash.util.ts
Labels: enhancement

#18 add: crud api for `session`
  prisma/migrations/20250215040829_create_session_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.module.ts
  src/domains/courses/sessions/dto/create-session.dto.ts
  src/domains/courses/sessions/dto/update-session.dto.ts
  src/domains/courses/sessions/sessions.controller.ts
  src/domains/courses/sessions/sessions.module.ts
  src/domains/courses/sessions/sessions.service.ts
Labels: enhancement

#20 add: crud api for `lecture` & optimize code
  prisma/migrations/20250216020109_update_course_model_and_change_name_model_section/migration.sql
  prisma/migrations/20250216022954_create_lecture_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.module.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/dto/create-course.dto.ts
  src/domains/courses/sections/dto/create-section.dto.ts
  src/domains/courses/sections/dto/update-section.dto.ts
  src/domains/courses/sections/lectures/dto/create-lecture.dto.ts
  src/domains/courses/sections/lectures/dto/update-lecture.dto.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/lectures/lectures.module.ts
  src/domains/courses/sections/lectures/lectures.service.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/courses/sections/sections.module.ts
  src/domains/courses/sections/sections.service.ts
  src/domains/courses/sessions/dto/update-session.dto.ts
  src/domains/courses/sessions/sessions.controller.ts
  src/domains/courses/sessions/sessions.module.ts
  src/domains/courses/sessions/sessions.service.ts
Labels: enhancement

#21 [BE] Implement CRUD for Lecture API in each Section
  prisma/migrations/20250216020109_update_course_model_and_change_name_model_section/migration.sql
  prisma/migrations/20250216022954_create_lecture_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.module.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/dto/create-course.dto.ts
  src/domains/courses/sections/dto/create-section.dto.ts
  src/domains/courses/sections/dto/update-section.dto.ts
  src/domains/courses/sections/lectures/dto/create-lecture.dto.ts
  src/domains/courses/sections/lectures/dto/update-lecture.dto.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/lectures/lectures.module.ts
  src/domains/courses/sections/lectures/lectures.service.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/courses/sections/sections.module.ts
  src/domains/courses/sections/sections.service.ts
  src/domains/courses/sessions/dto/update-session.dto.ts
  src/domains/courses/sessions/sessions.controller.ts
  src/domains/courses/sessions/sessions.module.ts
  src/domains/courses/sessions/sessions.service.ts
Labels: enhancement

#22 release: release v1.1.0
  .github/workflows/build.yml
  package.json
  prisma/migrations/20250214035414_create_course_table/migration.sql
  prisma/migrations/20250215040829_create_session_model/migration.sql
  prisma/migrations/20250216020109_update_course_model_and_change_name_model_section/migration.sql
  prisma/migrations/20250216022954_create_lecture_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.module.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/dto/create-course.dto.ts
  src/domains/courses/dto/update-course.dto.ts
  src/domains/courses/sections/dto/create-section.dto.ts
  src/domains/courses/sections/dto/update-section.dto.ts
  src/domains/courses/sections/lectures/dto/create-lecture.dto.ts
  src/domains/courses/sections/lectures/dto/update-lecture.dto.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/lectures/lectures.module.ts
  src/domains/courses/sections/lectures/lectures.service.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/courses/sections/sections.module.ts
  src/domains/courses/sections/sections.service.ts
  src/domains/domains.module.ts
  tsconfig.json
Labels: documentation, enhancement, good first issue

#24 Patch for task 23
  CONTRIBUTING.md
  src/configs/payos.config.ts
  src/domains/orders/orders.service.ts
  src/domains/payments/config/payos.config.ts
  src/domains/payments/payments.module.ts
  src/domains/payments/payments.service.ts
Labels: bug, documentation, enhancement

#25 [BE] Implement API Payment Course
  CONTRIBUTING.md
  prisma/migrations/20250222024555_create_order_and_payment_model/migration.sql
  prisma/migrations/20250223043759_update_relationship_between_course_and_user_models/migration.sql
  prisma/migrations/20250223132529_remove_payment_method_in_payment_model/migration.sql
  prisma/migrations/20250223134949_update_payment_model/migration.sql
  prisma/migrations/20250224020255_update_order_and_payment_models/migration.sql
  prisma/migrations/20250224062033_update_ref_name/migration.sql
  prisma/schema.prisma
  src/configs/payos.config.ts
  src/domains/domains.module.ts
  src/domains/orders/dto/create-order.dto.ts
  src/domains/orders/dto/update-order.dto.ts
  src/domains/orders/orders.controller.ts
  src/domains/orders/orders.module.ts
  src/domains/orders/orders.service.ts
  src/domains/payments/dto/create-payment.dto.ts
  src/domains/payments/dto/update-payment.dto.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.module.ts
  src/domains/payments/payments.service.ts
  tsconfig.json
Labels: enhancement

#28 dev: release api v1.2.0
  CONTRIBUTING.md
  package.json
  prisma/migrations/20250222024555_create_order_and_payment_model/migration.sql
  prisma/migrations/20250223043759_update_relationship_between_course_and_user_models/migration.sql
  prisma/migrations/20250223132529_remove_payment_method_in_payment_model/migration.sql
  prisma/migrations/20250223134949_update_payment_model/migration.sql
  prisma/migrations/20250224020255_update_order_and_payment_models/migration.sql
  prisma/migrations/20250224062033_update_ref_name/migration.sql
  prisma/schema.prisma
  src/configs/payos.config.ts
  src/domains/domains.module.ts
  src/domains/orders/dto/create-order.dto.ts
  src/domains/orders/dto/update-order.dto.ts
  src/domains/orders/orders.controller.ts
  src/domains/orders/orders.module.ts
  src/domains/orders/orders.service.ts
  src/domains/payments/dto/create-payment.dto.ts
  src/domains/payments/dto/update-payment.dto.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.module.ts
  src/domains/payments/payments.service.ts
  tsconfig.json
Labels: documentation, enhancement, good first issue

#33 feat: add get normal id for user (learn & teacher)
  src/domains/domains.module.ts
  src/domains/orders/orders.controller.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.module.ts
  src/domains/users/users.service.ts
  tsconfig.json
Labels: documentation, enhancement, good first issue

#35 release: release v1.3.0
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  src/domains/domains.module.ts
  src/domains/orders/orders.controller.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.module.ts
  src/domains/users/users.service.ts
  src/main.ts
  tsconfig.json
Labels: documentation, enhancement, good first issue

#36 hotfix: optimize payment api & add become a teacher api
  package.json
  prisma/migrations/20250226052639_replace_order_to_payment/migration.sql
  prisma/migrations/20250226072917_modify_payment_model_to_allow_optional_course/migration.sql
  prisma/schema.prisma
  src/domains/domains.module.ts
  src/domains/orders/dto/create-order.dto.ts
  src/domains/orders/dto/update-order.dto.ts
  src/domains/orders/orders.controller.ts
  src/domains/orders/orders.module.ts
  src/domains/orders/orders.service.ts
  src/domains/payments/dto/create-payment.dto.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.module.ts
  src/domains/payments/payments.service.ts
  src/domains/payments/payos.service.ts
  src/domains/users/dto/become-a-teacher.dto.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.module.ts
  src/domains/users/users.service.ts
  tsconfig.json
Labels: enhancement, good first issue

#38 [BE] Implement API for Learning Course
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250226040934_create_progress_model/migration.sql
  prisma/migrations/20250226052639_replace_order_to_payment/migration.sql
  prisma/migrations/20250226072917_modify_payment_model_to_allow_optional_course/migration.sql
  prisma/migrations/20250226133021_update_progress_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/domains.module.ts
  src/domains/orders/dto/create-order.dto.ts
  src/domains/orders/dto/update-order.dto.ts
  src/domains/orders/orders.controller.ts
  src/domains/orders/orders.module.ts
  src/domains/orders/orders.service.ts
  src/domains/payments/dto/create-payment.dto.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.module.ts
  src/domains/payments/payments.service.ts
  src/domains/payments/payos.service.ts
  src/domains/users/dto/become-a-teacher.dto.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.module.ts
  src/domains/users/users.service.ts
  src/main.ts
  tsconfig.json
Labels: enhancement, good first issue

#39 [BE] Implement API for Learning Course
  package.json
  prisma/migrations/20250226040934_create_progress_model/migration.sql
  prisma/migrations/20250226133021_update_progress_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/payments/payos.service.ts
Labels: enhancement, good first issue

#40 dev: release api v1.4.0
  package.json
  prisma/migrations/20250226040934_create_progress_model/migration.sql
  prisma/migrations/20250226133021_update_progress_model/migration.sql
  prisma/schema.prisma
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
  src/domains/courses/sections/lectures/lectures.controller.ts
  src/domains/courses/sections/sections.controller.ts
  src/domains/payments/payos.service.ts
Labels: documentation, enhancement, good first issue

#41 update: refactor user retrieval methods to support flexible identifier handling
  package.json
  src/domains/users/users.controller.ts
  src/domains/users/users.service.ts
Labels: enhancement, good first issue

#43 release: release v1.4.2
  package.json
  src/domains/users/users.controller.ts
  src/domains/users/users.service.ts
Labels: documentation, enhancement, good first issue

#44 add: api get courses by teacherId
  package.json
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
Labels: enhancement, good first issue

#45 add: api get courses by teacherId
  package.json
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
Labels: enhancement, good first issue

#46 dev: release api v1.4.3
  package.json
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
Labels: good first issue

#47 update: implement api get top teachers & get all lectures by course id
  package.json
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.service.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.service.ts
Labels: enhancement, good first issue

#48 update: release api v1.4.4
  package.json
  src/domains/courses/courses.controller.ts
  src/domains/courses/courses.service.ts
  src/domains/payments/payments.controller.ts
  src/domains/payments/payments.service.ts
  src/domains/users/users.controller.ts
  src/domains/users/users.service.ts
Labels: enhancement, good first issue
